"""EvoQuant - Genetic Programming for Trading Strategy Evolution"""

from evoquant.base import (
    SeriesBase,
    SeriesFloat,
    SeriesBool,
    SeriesDate,
    SeriesPrice,
    SeriesIndicator,
    SeriesOpen,
    SeriesHigh,
    SeriesLow,
    SeriesClose,
    SeriesVolume,
    ParameterBase,
    Period,
    Lag,
)

from evoquant.signals import (
    and_rule,
    and_rule3,
    and_rule4,
    or_rule,
    or_rule3,
    or_rule4,
    xor_rule,
    xor_rule3,
    xor_rule4,
    not_rule,
    cross_above_rule,
    cross_below_rule,
    is_above_rule,
    is_below_rule,
    series_above_value_rule,
    series_below_value_rule,
    series_above_shift_rule,
    series_below_shift_rule,
    series_cross_above_shift_rule,
    series_cross_below_shift_rule,
    series_above_ma_rule,
    series_below_ma_rule,
    series_cross_above_ma_rule,
    series_cross_below_ma_rule,
    series_above_quantile_rule,
    series_below_quantile_rule,
    series_cross_above_quantile_rule,
    series_cross_below_quantile_rule,
    and2_or1,
    and3_or1,
    and2_or2,
    and3_or2,
    and3_or3,
    and4_or1,
)

from evoquant.indicators import (
    shift,
    sum_indicator,
    diff,
    abs_value,
    abs_diff,
    sma,
    highest,
    lowest,
    rsi,
    zscore,
    bbands,
    RSI,
    ZScore,
    RSIValue,
    ZScoreValue,
)

from evoquant.orchestrator import Orchestrator, Evolver

from evoquant.backtest_engine import EvoStrategy

from evoquant.translator_engine import PTTranslator, CTraderTranslator

__all__ = [
    # Base types
    "SeriesBase",
    "SeriesFloat",
    "SeriesBool",
    "SeriesDate",
    "SeriesPrice",
    "SeriesIndicator",
    "SeriesOpen",
    "SeriesHigh",
    "SeriesLow",
    "SeriesClose",
    "SeriesVolume",
    "ParameterBase",
    "Period",
    "Lag",
    # Signals
    "and_rule",
    "and_rule3",
    "and_rule4",
    "or_rule",
    "or_rule3",
    "or_rule4",
    "xor_rule",
    "xor_rule3",
    "xor_rule4",
    "not_rule",
    "cross_above_rule",
    "cross_below_rule",
    "is_above_rule",
    "is_below_rule",
    "series_above_value_rule",
    "series_below_value_rule",
    "series_above_shift_rule",
    "series_below_shift_rule",
    "series_cross_above_shift_rule",
    "series_cross_below_shift_rule",
    "series_above_ma_rule",
    "series_below_ma_rule",
    "series_cross_above_ma_rule",
    "series_cross_below_ma_rule",
    "series_above_quantile_rule",
    "series_below_quantile_rule",
    "series_cross_above_quantile_rule",
    "series_cross_below_quantile_rule",
    "and2_or1",
    "and3_or1",
    "and2_or2",
    "and3_or2",
    "and3_or3",
    "and4_or1",
    # Indicators
    "shift",
    "sum_indicator",
    "diff",
    "abs_value",
    "abs_diff",
    "sma",
    "highest",
    "lowest",
    "rsi",
    "zscore",
    "bbands",
    "RSI",
    "ZScore",
    "RSIValue",
    "ZScoreValue",
    # Orchestrator
    "Orchestrator",
    "Evolver",
    # Backtest Engine
    "EvoStrategy",
    # Translator Engine
    "PTTranslator",
    "CTraderTranslator",
]

__version__ = "0.1.0"
